services:
  # cassandra:
  #   image: 'cassandra:latest'
  #   environment:
  #     - 'CASSANDRA_DC=dc1'
  #     - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
  #   ports:
  #     - '9042'
  mongodb:
    image: 'mongo:7'
    environment:
      - 'MONGO_INITDB_DATABASE=app_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=9317'
      - 'MONGO_INITDB_ROOT_USERNAME=tripfy'
    ports:
      - '27017'
  # postgres:
  #   image: 'postgres:16'
  #   environment:
  #     - 'POSTGRES_DB=auth_db'
  #     - 'POSTGRES_PASSWORD=9317'
  #     - 'POSTGRES_USER=tripfy'
  #   ports:
  #     - '5432'
  redis:
    image: 'redis:7.2'
    ports:
      - '6379'
