spring.application.name=tripfy

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=tripfy
spring.datasource.password=9317

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect