spring.application.name=tripfy

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Env
spring.config.import=optional:file:.env[.properties]

# Google
google.places.api-key=${GOOGLE_PLACES_API_KEY}
oauth.google.client-id=${GOOGLE_CLIENT_ID}

# Apple
oauth.apple.bundle-id=${APPLE_BUNDLE_ID}

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-minutes=60
# jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=7



# PPPP   OOOOOOOOO  SSSSSSS  TTTTTTTTT  GGGGGGGG  RRRRRR   EEEEEEEE  SSSSSSS            SSSSSSS   QQQQQQQ     L
# P   P  O       O  S            T      G         R     R  E         S                  S        Q       Q    L
# P   P  O       O  S            T      G         R     R  E         S                  S        Q       Q    L
# PPPP   O       O  SSSSSSS      T      G   GGG   RRRRRR   EEEEEEEE  SSSSSSS            SSSSSSS  Q       Q    L
# P      O       O        S      T      G      G  R   R    E               S                  S  Q     Q Q    L
# P      O       O        S      T      G      G  R    R   E               S                  S  Q      QQ    L
# P      OOOOOOOOO  SSSSSSS      T       GGGGGG   R     R  EEEEEEEE  SSSSSSS            SSSSSSS   QQQQQQQQ    LLLLLLLL
#                                                                                                         Q  
#                                                                                                          Q  

# Datasource SELECT POSTGRESQL
db.select.url=jdbc:postgresql://localhost:5432/tripfy
db.select.username=${POSTGRES_SELECT_USERNAME}
db.select.password=${POSTGRES_SELECT_PASSWORD}

# Datasource INSERT
db.insert.url=jdbc:postgresql://localhost:5432/tripfy
db.insert.username=${POSTGRES_INSERT_USERNAME}
db.insert.password=${POSTGRES_INSERT_PASSWORD}

# Datasource UPDATE
db.update.url=jdbc:postgresql://localhost:5432/tripfy
db.update.username=${POSTGRES_UPDATE_USERNAME}
db.update.password=${POSTGRES_UPDATE_PASSWORD}

# Datasource DELETE
db.delete.url=jdbc:postgresql://localhost:5432/tripfy
db.delete.username=${POSTGRES_DELETE_USERNAME}
db.delete.password=${POSTGRES_DELETE_PASSWORD}

# Migration
spring.liquibase.url=jdbc:postgresql://localhost:5432/tripfy
spring.liquibase.user=${POSTGRES_MIGRATION_USERNAME}
spring.liquibase.password=${POSTGRES_MIGRATION_PASSWORD}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Liquibase parameters
spring.liquibase.parameters.apiSelectPassword=${POSTGRES_SELECT_PASSWORD}
spring.liquibase.parameters.apiInsertPassword=${POSTGRES_INSERT_PASSWORD}
spring.liquibase.parameters.apiUpdatePassword=${POSTGRES_UPDATE_PASSWORD}
spring.liquibase.parameters.apiDeletePassword=${POSTGRES_DELETE_PASSWORD}



# M       M  OOOOOOOOO  N      N   GGGGGG   OOOOOOOOO            DDDDDDD   BBBBBBB 
# MM     MM  O       O  NN     N  G         O       O            D      D  B      B
# M M   M M  O       O  N N    N  G         O       O            D       D B      B
# M  M M  M  O       O  N  N   N  G   GGG   O       O            D       D BBBBBBB 
# M   M   M  O       O  N   N  N  G      G  O       O            D       D B      B
# M       M  O       O  N    N N  G      G  O       O            D      D  B      B
# M       M  OOOOOOOOO  N     NN   GGGGGG   OOOOOOOOO            DDDDDDD   BBBBBBB 

#


