spring.application.name=tripfy

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Env
spring.config.import=optional:file:.env[.properties]

# Google
google.places.api-key=${GOOGLE_PLACES_API_KEY}

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=7

# Datasource SELECT
db.select.url=jdbc:postgresql://localhost:5432/tripfy
db.select.username=${SELECT_USERNAME}
db.select.password=${SELECT_PASSWORD}

# Datasource INSERT
db.insert.url=jdbc:postgresql://localhost:5432/tripfy
db.insert.username=${INSERT_USERNAME}
db.insert.password=${INSERT_PASSWORD}

# Datasource UPDATE
db.update.url=jdbc:postgresql://localhost:5432/tripfy
db.update.username=${UPDATE_USERNAME}
db.update.password=${UPDATE_PASSWORD}

# Datasource DELETE
db.delete.url=jdbc:postgresql://localhost:5432/tripfy
db.delete.username=${DELETE_USERNAME}
db.delete.password=${DELETE_PASSWORD}


# Migration
spring.liquibase.url=jdbc:postgresql://localhost:5432/tripfy
spring.liquibase.user=${MIGRATION_USERNAME}
spring.liquibase.password=${MIGRATION_PASSWORD}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Liquibase parameters
spring.liquibase.parameters.apiSelectPassword=${SELECT_PASSWORD}
spring.liquibase.parameters.apiInsertPassword=${INSERT_PASSWORD}
spring.liquibase.parameters.apiUpdatePassword=${UPDATE_PASSWORD}
spring.liquibase.parameters.apiDeletePassword=${DELETE_PASSWORD}


oauth.google.client-id=113803906790-7qllk5o8b2ked80qpajo7vvfjnar8tkf.apps.googleusercontent.com
oauth.apple.bundle-id=${APPLE_BUNDLE_ID}